<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Laporan Trendora</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #1e293b;
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }

        .logo {
            font-size: 28px;
            font-weight: bold;
            color: #6366f1;
        }

        .sub {
            font-size: 12px;
            color: #64748b;
        }

        .title {
            background: linear-gradient(90deg, #6366f1, #8b5cf6);
            color: white;
            padding: 10px;
            border-radius: 8px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            background: #6366f1;
            color: white;
            padding: 10px;
            font-size: 12px;
        }

        td {
            padding: 10px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 12px;
        }

        .badge {
            padding: 4px 8px;
            border-radius: 6px;
            font-size: 11px;
            color: white;
        }

        .pending {
            background: #f59e0b;
        }

        .process {
            background: #3b82f6;
        }

        .done {
            background: #22c55e;
        }

        .cancel {
            background: #ef4444;
        }

        .summary {
            margin-top: 20px;
            display: flex;
            justify-content: space-between;
        }

        .box {
            width: 48%;
            background: #f8fafc;
            padding: 15px;
            border-radius: 10px;
        }

        .box-title {
            font-size: 12px;
            color: #64748b;
        }

        .box-value {
            font-size: 20px;
            font-weight: bold;
            margin-top: 5px;
        }

        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 11px;
            color: #64748b;
        }
    </style>
</head>

<body>

    <div class="header">

        <div>
            <div class="logo">Trendora</div>
            <div class="sub">Laporan Pesanan Customer</div>
        </div>

        <div class="sub">
            Exported:<br>
            {{ $exportedAt->format('d M Y H:i') }}
        </div>

    </div>

    <div class="title">
        Data Pesanan
    </div>

    <table>

        <thead>
            <tr>
                <th>ID</th>
                <th>Tanggal</th>
                <th>Cabang</th>
                <th>Pembayaran</th>
                <th>Status</th>
                <th>Total</th>
            </tr>
        </thead>

        <tbody>

            @foreach ($orders as $order)
                <tr>

                    <td>#{{ $order->id }}</td>

                    <td>
                        {{ $order->created_at->format('d M Y') }}
                    </td>

                    <td>
                        {{ $order->branch->name ?? '-' }}
                    </td>

                    <td>
                        {{ $order->paymentMethod->name ?? '-' }}
                    </td>

                    <td>

                        <span class="badge {{ $order->status }}">
                            {{ ucfirst($order->status) }}
                        </span>

                    </td>

                    <td>
                        Rp {{ number_format($order->total_price, 0, ',', '.') }}
                    </td>

                </tr>
            @endforeach

        </tbody>

    </table>


    <div class="summary">

        <div class="box">

            <div class="box-title">
                Total Pesanan
            </div>

            <div class="box-value">
                {{ $totalOrders }}
            </div>

        </div>


        <div class="box">

            <div class="box-title">
                Total Pembayaran
            </div>

            <div class="box-value">
                Rp {{ number_format($totalAmount, 0, ',', '.') }}
            </div>

        </div>

    </div>


    <div class="footer">

        Generated by Trendora System<br>
        © {{ date('Y') }} Trendora

    </div>

</body>

</html>
